kind: pipeline
name: default

steps:
  # Restore the cache if it exists
  - name: load-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: bip-drone-dependency-cache
      json_key:
        from_secret: gcs_credentials
      restore: true

  - name: restore-cache
    image: maven:3-jdk-11
    commands:
      - mkdir -p /drone/src/.m2
      - mkdir -p /drone/src/drone/src/.m2/repository
      - mv /drone/src/drone/src/.m2/repository /drone/src/.m2/
      - rm -rf /drone/src/drone/src/.m2
    depends_on:
      - load-cache

  - name: authenticate
    image: robertstettner/drone-mvn-auth
    pull: always
    settings:
      servers:
        from_secret: maven_servers
      profiles:
        - id: ssb-bip
          repositories:
            - id: ssb-bip-releases
              url: https://nexus.prod-bip-ci.ssb.no/repository/maven-releases/
              layout: default
            - id: ssb-bip-snapshots
              url: https://nexus.prod-bip-ci.ssb.no/repository/maven-snapshots/
              layout: default

  - name: build
    image: maven:3-jdk-11
    commands:
      - mvn compile -P ssb-bip -Dmaven.repo.local=/drone/src/.m2/repository -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --global-settings settings.xml
    depends_on:
      - authenticate
      - restore-cache

  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn verify test -P ssb-bip,coverage -Dmaven.repo.local=/drone/src/.m2/repository --batch-mode --global-settings settings.xml
    depends_on:
      - build

  - name: sonarqube
    image: maven:3-jdk-11
    commands:
      - mvn -X -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_PROJECTKEY sonar:sonar -P ssb-bip,coverage -Dmaven.repo.local=/drone/src/.m2/repository -Dmaven.javadoc.skip=true --batch-mode --global-settings settings.xml
    environment:
      SONAR_HOST_URL: https://sonarqube.prod-bip-ci.ssb.no
      SONAR_PROJECTKEY:
        from_secret: sonar_token
    depends_on:
      - test

  - name: publish-maven
    image: maven:3-jdk-11
    commands:
      - mvn clean deploy -P ssb-bip, -Dmaven.repo.local=/drone/src/.m2/repository -DskipTests=true --batch-mode --global-settings settings.xml
    when:
      ref:
        - refs/tags/*
    depends_on:
      - sonarqube

  - name: publish-docker
    image: plugins/gcr
    settings:
      repo: prod-bip/rawdata-converter-app-sirius
      registry: eu.gcr.io
      tags: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
      json_key:
        from_secret: gcr_credentials
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - sonarqube

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: bip-ci-test
    when:
      status: [ success, failure ]
    depends_on:
      - publish-maven

  # Rebuild cache if it has changed with this build
  - name: rebuild-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: bip-drone-dependency-cache
      json_key:
        from_secret: gcs_credentials
      rebuild: true
      mount:
        - /drone/src/.m2/repository
    depends_on:
      - publish-maven

  # OPTIONAL: Flush the cache of old cache items (older than 14 days)
  - name: flush-cache
    image: homerovalle/drone-gcs-cache
    settings:
      pull: true
      bucket: bip-drone-dependency-cache
      json_key:
        from_secret: gcs_credentials
      flush: true
      flush_age: 14
    depends_on:
      - publish-maven
---
kind: secret
name: maven_servers
get:
  path: drone-maven-servers
  name: ssb-bip-maven-servers

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url
---
kind: secret
name: sonar_host
get:
  path: drone-sonarqube-configuration
  name: url
---
kind: secret
name: sonar_token
get:
  path: drone-sonarqube-configuration
  name: token
---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials
---
kind: secret
name: gcs_credentials
get:
  path: drone-gcs-credentials
  name: gcs-credentials
