micronaut:
  application.name: rawdata-converter-app-sirius
  server.port: 28083

endpoints:
  all:
    # Uncomment to open all management endpoints - https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
    sensitive: false

rawdata.client:
  provider: gcs
  local-temp-folder: temp
  avro-file:
    max.seconds: 3600
    max.bytes: 10485760
    sync.interval: 500000
  gcs:
    bucket-name: dev-rawdata-store
    listing.min-interval-seconds: 15
    service-account.key-file: ../localenv/auth/gcs/dev-bip/gcs_credentials.json

#rawdata.storage:
#  encryption:
#    key: SECURE_KMS_TOKEN
#    salt: somesalt

rawdata.converter:
  storage-type: gcs
  storage-root: gs://dev-rawdata-store/data-dev
  storage-path: converted/sirius
  topic: sirius-person-utkast
  window-max-records: 100
  window-max-time-in-seconds: 60
  initial-position: FIRST
  dataset-metadata:
    valuation: INTERNAL
    state: INPUT
  pseudo:
    config:
      var-funcs:
        personidentifikator: fpe-fnr(secret1)
        organisasjonsnummer: fpe-digits(secret2)
    secrets:
      repo:
        secret1:
          content: C5sn7B4YtwcilAwuVx6NuAsMWLusOSA/ldia40ZugDI=
          type: AES256
        secret2:
          content: CsR1rI/27ejUOSltjQiBDdGeqTY5sy0Af9Tf7E/WYBU=
          type: AES256

rawdata.converter.app.sirius:
  schema-file-skattemelding: schema/sirius-skattemelding-v19.avsc