micronaut:
  application.name: rawdata-converter-app-sirius
  server.port: 28083

endpoints:
  all:
    # Uncomment to open all management endpoints - https://docs.micronaut.io/latest/guide/index.html#providedEndpoints
    sensitive: false

rawdata.client:
  provider: gcs
  local-temp-folder: temp
  avro-file:
    max.seconds: 3600
    max.bytes: 10485760
    sync.interval: 500000
  gcs:
    bucket-name: dev-rawdata-store
    listing.min-interval-seconds: 15
    credential-provider: service-account
    service-account.key-file: ../localenv/auth/gcs/dev-bip/gcs_credentials.json

rawdata.encryption:
    key: SECURE_KMS_TOKEN
    salt: SALT

rawdata.converter:
  active-by-default: true
  storage-type: gcs
  storage-root: gs://dev-rawdata-store/datastore
  storage-path: /kilde/ske/skatt/person/fastsatt/rådata/2018v0.22
  storage-version: 1585232479000
  service-account-key-file: ../localenv/auth/gcs/dev-bip/gcs_credentials.json
  topic: sirius-person-fastsatt
  window-max-records: 1000
  window-max-time-in-seconds: 60
  initial-position: FIRST
  dataset-meta:
    valuation: INTERNAL
    type: UNBOUNDED
  pseudo:
    secrets:
      repo:
        secret1:
          content: C5sn7B4YtwcilAwuVx6NuAsMWLusOSA/ldia40ZugDI=
          type: AES256
        secret2:
          content: CsR1rI/27ejUOSltjQiBDdGeqTY5sy0Af9Tf7E/WYBU=
          type: AES256
    config:
      debug: true
      rules:
        personidentifikator:
          pattern: '**/personidentifikator'
          func: fpe-fnr(secret1)
        navn:
          pattern: '**/{bidragsytersNavn,bidragsmottakersNavn,barnSomGirRettTilForeldrefradrag/navn}'
          func: fpe-letters_no+whitespace(secret1)
        kontonummer:
          pattern: '**/kontonummer'
          func: fpe-digits+.(secret1)
        kjoeretoey:
          pattern: '**/kjoeretoey/registreringsnummer'
          func: fpe-alphanumeric(secret1)
        eiendom1:
          pattern: '**/eiendom*/{bruksnavn,gateadresse,boligselskapetsNavn}'
          func: fpe-alphanumeric_no+whitespace(secret1)
        eiendom2:
          pattern: '**/eiendom*/{*nummer}'
          func: fpe-digits(secret1)
        ostepop:
          pattern: '**/ostepop/ost'
          func: fpe-digits(secret1)

rawdata.converter.app.sirius:
  schema-file-skattemelding: schema/sirius-skattemelding-utflatet-2018_v0.22.avsc
  schema-file-hendelse: schema/sirius-hendelse_v1.3.avsc
  gjelder-periode: 2018
