rawdata.converter.pseudo:
  secrets:
    repo:
      secret1:
        content: C5sn7B4YtwcilAwuVx6NuAsMWLusOSA/ldia40ZugDI=
        type: AES256
      secret2:
        content: CsR1rI/27ejUOSltjQiBDdGeqTY5sy0Af9Tf7E/WYBU=
        type: AES256
