micronaut:
  application.name: rawdata-converter-app-sirius
  server.port: 8080

rawdata.client:
  provider: gcs
  local-temp-folder: temp
  avro-file:
    max.seconds: 3600
    max.bytes: 10485760
    sync.interval: 500000
  gcs:
    bucket-name: staging-rawdata-store
    listing.min-interval-seconds: 15
    service-account.key-file: /run/ssb/secrets/gcs_credentials.json

rawdata.converter:
  active-by-default: true
  storage-type: gcs
  storage-root: gs://ssb-data-staging
  storage-path: /raw/ske/skatt/sirius-person-utkast/2018v19/1583156472183
  topic: sirius-person-utkast
  window-max-records: 100000
  window-max-time-in-seconds: 300
  initial-position: LAST
  dataset-meta:
    valuation: INTERNAL
    type: UNBOUNDED
  pseudo:
    config:
      var-funcs:
        personidentifikator: fpe-fnr(secret1)
        organisasjonsnummer: fpe-digits(secret1)
    secrets:
      repo:
        secret1:
          # TODO: Replace with a real secret.
          # TODO: The real one should be provided via RAWDATA_CONVERTER_PSEUDO_SECRETS_REPO_SECRET1_CONTENT in staging.
          content: C5sn7B4YtwcilAwuVx6NuAsMWLusOSA/ldia40ZugDI=
          type: AES256

rawdata.converter.app.sirius:
  schema-file-skattemelding: schema/sirius-skattemelding-utflatet-2018_v19.avsc
  schema-file-hendelse: schema/sirius-hendelse_v1.1.avsc
  gjelder-periode: 2018
